### ISSUE TITLE
PRACTICA3_ 

### ISSUE THREAD

**Issue by Nelsy21** [SistemasTecTlaxiaco/actividad-9-practica-de-seguimiento-y-control-de-proyecto-equipo-m#1]
[Practica9_Unidad3_Gestion_de_proyectos.pdf](https://github.com/user-attachments/files/17498228/Practica9_Unidad3_Gestion_de_proyectos.pdf)

**Comment by carlos0716c** [comment]
portada y los escudos institucionales: 25 puntos
Describe el procedimiento: 25 puntos
Incluye ilustraciones y capturas: 25 puntos
Conclusión: 25 puntos
Puntaje alcanzado 100% = 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado..

**Comment by josealfredo79** [comment]
Falta el link del proyecto
